apiVersion: v1
#Object type being type Secret
kind: Secret
metadata:
#name of the secret after this it will be used at Deployment like this: secretRef
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=
