apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  type: NodePort               # Permite acesso externo fora do cluster
  selector:
    app: spring-app-dev            # Seleciona os pods do Deployment tem que ser o nome do pod
  ports:
    - port: 8080               # Porta interna do Service (do cluster)
      targetPort: 8080         # Porta do container
      nodePort: 30080          # Porta que ficará acessível externamente
